version: "3.4"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "l7JX1m3p"
      MSSQL_PID: "Express"
    ports:
      - "1412:1433" 
      
#  money-track-service:
#      image: ${DOCKER_REGISTRY-}money-track-service
#      ports:
#        - 2022:2022      
#      networks:
#        - mt-bridge-network
#      build:
#          context: .
#          dockerfile: ./MoneyTrack/Dockerfile
        
networks:
    mt-bridge-network:
        external: true