version: "3.8"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "l7JX1m3p"
      MSSQL_PID: "Express"
    ports:
      - "1412:1433" 
      
  money-track-service:
      image: money-track-service
      build:
          context: ./src
          dockerfile: ./MoneyTrack/Dockerfile
      ports:
        - 2022:2022